importing libraries

In [1]:
import pandas as pd
import numpy as np

Importing The Data

In [2]:
df=pd.read_csv('retail_store_sales.csv')

In [5]:
df.shape[0]

12575

In [9]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

In [10]:
df['Transaction ID'].nunique()

12575

In [11]:
df['Customer ID'].nunique()

25

In [20]:
df['Customer ID'].isna().sum()

np.int64(0)

In [12]:
df['Customer ID'].unique()

array(['CUST_09', 'CUST_22', 'CUST_02', 'CUST_06', 'CUST_05', 'CUST_07',
       'CUST_21', 'CUST_23', 'CUST_25', 'CUST_14', 'CUST_15', 'CUST_17',
       'CUST_01', 'CUST_10', 'CUST_04', 'CUST_13', 'CUST_18', 'CUST_08',
       'CUST_20', 'CUST_12', 'CUST_11', 'CUST_19', 'CUST_16', 'CUST_24',
       'CUST_03'], dtype=object)

In [13]:
df['Category'].unique()

array(['Patisserie', 'Milk Products', 'Butchers', 'Beverages', 'Food',
       'Furniture', 'Electric household essentials',
       'Computers and electric accessories'], dtype=object)

In [29]:
df['Category'].isna().sum()

np.int64(0)

In [21]:
df['Category'].isna().sum()

np.int64(0)

In [30]:
df['Price Per Unit'].isna().sum()

np.int64(609)

In [31]:
df['Price Per Unit'].unique()

array([18.5, 29. , 21.5, 27.5, 12.5,  nan,  5. , 33.5, 36.5,  8. ,  6.5,
       39.5, 24.5, 23. , 35. , 14. ,  9.5, 41. , 20. , 38. , 15.5, 11. ,
       32. , 26. , 30.5, 17. ])

In [15]:
df['Item'].unique()
df['Item'].nunique()

200

In [22]:
df['Item'].isna().sum()

np.int64(1213)

In [16]:
df['Quantity'].unique()

array([10.,  9.,  2.,  7.,  8., nan,  1.,  3.,  6.,  4.,  5.])

In [17]:
df['Quantity'].dtype

dtype('float64')

In [23]:
df['Quantity'].isna().sum()

np.int64(604)

In [19]:
df['Total Spent'].unique()

array([185. , 261. ,  43. , 247.5,  87.5, 200. ,  40. ,   nan,  27.5,
       109.5,  72. ,  52. ,  45.5, 237. ,  55. , 232. , 275. ,  23. ,
       126. , 105. ,  66.5,  18.5,  49. , 134. , 410. , 245. , 182.5,
       100. , 196. , 315. , 287. ,  76. ,  92.5, 190. , 255.5, 276.5,
        46.5,   8. , 107.5, 165. ,  80. , 192.5, 335. ,  66. , 215. ,
        96. ,  42. ,  11. , 234. , 316. ,  82.5, 180. , 365. ,  39. ,
       172. , 122. ,  30. ,  84. , 320. , 219. ,  67. , 146. , 290. ,
        70. , 160. ,  82. ,  14. , 355.5, 124. ,  28.5,  47.5, 193.5,
        38. ,  12.5, 140. , 120. , 183. , 305. ,  41. , 155. ,  19.5,
        33. , 108.5, 119. , 280. ,  62. ,  32. , 380. , 304. , 139.5,
       114. , 192. , 167.5,  88. , 395. , 158. ,  25. ,  50. ,  32.5,
        15. ,  33.5,  24. , 111. ,  46. ,  36.5,  62.5, 161. ,  26. ,
        98. ,  85. , 228. ,  91.5,  93. ,  35. , 208. , 100.5,   9.5,
        10. , 138. , 288. ,  60. , 123. ,  73. , 197.5,  69. ,  61. ,
       116. ,  55.5,

In [24]:
df['Total Spent'].isna().sum()

np.int64(604)

In [25]:
df['Payment Method'].unique()

array(['Digital Wallet', 'Credit Card', 'Cash'], dtype=object)

In [26]:
df['Transaction Date'].unique()

array(['2024-04-08', '2023-07-23', '2022-10-05', ..., '2023-03-17',
       '2024-02-29', '2022-09-16'], dtype=object)

In [27]:
df['Transaction Date'].isna().sum()

np.int64(0)

In [28]:
df['Discount Applied'].isna().sum()

np.int64(4199)

Getting the mappings from category to item column to fill the null rows in the item column

In [8]:
df['Category'].nunique()

8

In [4]:
df['Item'].unique()

array(['Item_10_PAT', 'Item_17_MILK', 'Item_12_BUT', 'Item_16_BEV',
       'Item_6_FOOD', nan, 'Item_1_FOOD', 'Item_16_FUR', 'Item_22_BUT',
       'Item_3_BUT', 'Item_2_FOOD', 'Item_24_PAT', 'Item_16_MILK',
       'Item_17_PAT', 'Item_13_EHE', 'Item_7_BEV', 'Item_4_EHE',
       'Item_10_FOOD', 'Item_14_FUR', 'Item_20_BUT', 'Item_25_FUR',
       'Item_14_FOOD', 'Item_22_PAT', 'Item_11_FOOD', 'Item_6_PAT',
       'Item_21_EHE', 'Item_25_BEV', 'Item_23_FOOD', 'Item_10_FUR',
       'Item_11_BEV', 'Item_23_BUT', 'Item_22_BEV', 'Item_10_EHE',
       'Item_24_BUT', 'Item_8_BEV', 'Item_3_FOOD', 'Item_12_FOOD',
       'Item_16_CEA', 'Item_11_PAT', 'Item_16_BUT', 'Item_5_CEA',
       'Item_19_MILK', 'Item_23_FUR', 'Item_7_FUR', 'Item_15_CEA',
       'Item_6_MILK', 'Item_24_CEA', 'Item_22_CEA', 'Item_22_FOOD',
       'Item_2_BUT', 'Item_14_PAT', 'Item_12_PAT', 'Item_18_FOOD',
       'Item_1_PAT', 'Item_4_BEV', 'Item_22_FUR', 'Item_7_PAT',
       'Item_20_CEA', 'Item_20_FOOD', 'Item_11_FUR', 'Item

In [5]:
df['Item'].isna().sum()

np.int64(1213)

In [7]:
df['Item'].nunique()

200